name: Doxygen GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  BUILD_TYPE: Release

jobs:
  publish:
    runs-on: windows-latest
    name: Build Release
    
    permissions:
      pages: write      
      id-token: write 
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive
        
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
        
      - name: Configure CMake
        run: cmake -S . -B ${{github.workspace}}/build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target doc_doxygen

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
        
      - name: Upload GH Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: ./build/Engine/docs/doc_doxygen/html
          retention-days: 5
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: doc_doxygen
          path: ./build/Engine/docs/doc_doxygen
          retention-days: 5
                    
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
